config/routes.rb
HowSoon::Application.routes.draw do

  match 'tweets' => 'site#tweets', :as => :tweets

   root :to => 'site#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
 require 'Twit'
 layout false, :except => :index
 before_filter :js_content_type, :only => [:js_content_type, :tweets]

  def js_content_type
    response.headers['Content-type'] = 'text/javascript; charset=utf-8'
  end

  def index
  end

  def tweets
    lyrics = Twit.new("#{Rails.root}/lib/lyrics_cut.txt")
    @tweets = lyrics.get_tweets
    respond_to do |format|
        format.html {render :partial => 'tweets'}
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper

  def rocking
    @tweets.each do |key, tweet|
      highlight =  highlight(tweet[0]['text'].to_s, key.to_s.humanize.downcase)
      haml_tag(:div, highlight)
       haml_tag(:br)
     end
  end

  def escape_single_quotes
   self.gsub(/[']/, '\\\\\'')
  end

  def tweets_help
   content = ''
   logger.debug "#fetched tweets : #{@tweets.to_yaml}"
   begin
   @tweets.each do |key, tweet|
     highlight =  " #{image_tag(tweet[:tweet][0]['profile_image_url'])} @#{tweet[:tweet][0]['from_user']} #{highlight(tweet[:tweet][0]['text'].to_s, key.to_s.humanize.downcase)}"
     content << "example.footnote({
        start: #{tweet[:start]},
        end: #{tweet[:stop]},
        text: '#{escape_javascript(highlight)}',
        target: 'footnote',
        effect: 'applyClass',
        applyClass: 'test2'
      }); "
   end
   rescue => e
   end

    return content
  end


end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HowSoon
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container_12
      = yield

app/views/site/_tweets.html.haml
-#-@tweets.each do |key, tweet|
-#  %div{:class => "footnote"}
-#    =highlight(tweet[0]['text'].to_s, key.to_s.humanize.downcase)

:javascript
  function DoTweets() {
     alert("tweets loaded!");
     $('#loading').hide("slow");
     var example = Popcorn.youtube(
     '#video',
     'http://www.youtube.com/watch?v=ojbEWJFF3Dw' );
     #{tweets_help}
     example.play();
    };

app/views/site/index.html.haml
-#.grid_12
-#  %h1
-#    %p HOW SOON IS NOW
-#.clear

#tweets_container

.grid_12
  #footnote

.grid_12
  #video{:style => 'width:960px; height:600px;'}
.clear

#link
  =link_to 'get tweets', tweets_path, :remote => true, :id => "get_tweets"
#loading{:style => 'display: none;'}
  loading

app/views/site/tweets.js.erb
//$('#tweets').html("<%#= escape_javascript(render :partial => 'tweets') %>");

    document.addEventListener("DOMContentLoaded", function () {
    var example = Popcorn.youtube(
    '#video',
    'http://www.youtube.com/watch?v=eHvbbJ0Sspc' );
    <% @tweets.each do |key, tweet|
          example.footnote({
            start: "#{start}",
            end: "#{start + 5}",
            text: highlight(tweet[0]['text'].to_s, key.to_s.humanize.downcase),
            target: "footnotediv"
          });
    end %>
  // play the video right away
    example.play();
    }, false);